name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'   # se actualiza cada día a medianoche UTC
  workflow_dispatch:        # también puedes lanzarlo a mano desde la pestaña Actions

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: jstrieb/github-stats@master
        with:
          username: carperca23
          exclude_repos: ""
          exclude_langs: ""
